name: garden
on:
  push:
    branches:
      - main
jobs:
  garden-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-central-1
      - uses: actions/checkout@v3.5.2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Start minikube
        uses: medyagh/setup-minikube@v0.0.13

      - name: Export kubeconfig for Garden
        run: echo ENCODED_KUBECONFIG=$(cat ~/.kube/config | base64 -w 0) >> "$GITHUB_ENV"

      - name: Build, tag, and push Docker image to Amazon ECR
        uses: garden-io/garden-action@v1.1
        with:
          command: >
            publish
          kubeconfig: ${{ env.ENCODED_KUBECONFIG }}